### PR TITLE
Update MIGX-Example

### PR DESCRIPTION
**Pull request by sebastian-marinescu**
Elaborating on the usage of Image+ in MIGX.

### CODE REVIEW

**Comment by Jako** [comment]
Thank you!

**Comment by sebastian-marinescu** [comment]
You are welcome!

**Comment by Jako** [comment]
The MIGX output could be done without the ImagePlus snippet, if the _Output TV Type_ could be set to `imageplus`. I hope this is possible in the MIGX configuration.

**Comment by sebastian-marinescu** [comment]
I tried to find it, but it seems not to exist in MIGX. On the formtab-fields you could change Input Options:

image

In the main field-tab you only set input/config options: 

image

So no way I know of setting the _Output TV Type_ inside MIGX.

**Comment by sebastian-marinescu** [comment]
Maybe @bruno17 could shed some light on this finding?

**Pull request merged**
